
package agh.sr.ws.calc.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://calc.ws.sr.agh/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddOperation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddOperation", targetNamespace = "http://calc.ws.sr.agh/", className = "agh.sr.ws.calc.jaxws.AddOperation")
    @ResponseWrapper(localName = "AddOperationResponse", targetNamespace = "http://calc.ws.sr.agh/", className = "agh.sr.ws.calc.jaxws.AddOperationResponse")
    public int addOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "DivideOperation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DivideOperation", targetNamespace = "http://calc.ws.sr.agh/", className = "agh.sr.ws.calc.jaxws.DivideOperation")
    @ResponseWrapper(localName = "DivideOperationResponse", targetNamespace = "http://calc.ws.sr.agh/", className = "agh.sr.ws.calc.jaxws.DivideOperationResponse")
    public double divideOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
